feature/about
kuzen0211/team-proj pull request #1
Opened 2022-08-12 16:13 UTC by KristinaBiba

2022-08-12 19:47 UTC, kuzen0211 requested changes

2022-08-12 19:47 UTC, kuzen0211 commented on src/partials/about.html
> +<section class="about">
Зміни, будь ласка, назву папки imageі/about на images

2022-08-13 14:38 UTC, KristinaBiba commented on src/partials/about.html
> +<section class="about">
Там є папка images, а у ній папка about. Воно так відображає, бо більше не має картинок у images. Додала svg у images, тепер все виглядає норм. Я її потім видалю.

2022-08-13 16:03 UTC, kuzen0211 approved these changes

2022-08-13 16:04 UTC, merged