add gellery
kuzen0211/team-proj pull request #2
Opened 2022-08-12 16:49 UTC by VitaliiSe

add gellery (html/css)

2022-08-12 20:06 UTC, kuzen0211 requested changes

2022-08-12 20:06 UTC, kuzen0211 commented on src/partials/gallery.html
> +<section class="gallery-conteiner">
Використовуй клас section. Я його створив

2022-08-12 20:06 UTC, kuzen0211 commented on src/partials/gallery.html
> +    <div class="gallery-conteiner__box  ">
Сміло використовуй клас container. Тільки пиши 'container' через букву 'a'

2022-08-12 20:06 UTC, kuzen0211 commented on src/sass/components/_gallery.scss
> +.conteiner{
ти створив стилі на цей клас хоча ніде його не використовуєш. У тебе ніде немає окремо такого класу

2022-08-13 05:06 UTC, VitaliiSe commented on src/partials/gallery.html
> +<section class="gallery-conteiner">
+

2022-08-13 05:06 UTC, VitaliiSe commented on src/sass/components/_gallery.scss
> +.conteiner{
+

2022-08-13 05:12 UTC, closed without merging