feature/header-hero-markup
kuzen0211/team-proj pull request #3
Opened 2022-08-12 16:49 UTC by srjCAJIO

розмітка хедера і хіро, створив папку images з базовими картинками

2022-08-12 19:30 UTC, kuzen0211 requested changes

2022-08-12 19:30 UTC, kuzen0211 commented on src/sass/index.css.map
> +{"version":3,"sources":["utils/_fonts.scss","index.css","utils/_common.scss","utils/_variables.scss","utils/_bace.scss","utils/_hidden.scss","utils/_container.scss"],"names":[],"mappings":"AAAA,cAAA;
Ми не користуємося SCSS компілятором. Видали зайві файли.  У парселі Репети scss автоматично компілюються.

2022-08-12 20:29 UTC, srjCAJIO commented on src/sass/index.css.map
> +{"version":3,"sources":["utils/_fonts.scss","index.css","utils/_common.scss","utils/_variables.scss","utils/_bace.scss","utils/_hidden.scss","utils/_container.scss"],"names":[],"mappings":"AAAA,cAAA;
выключил лайв сасс компилятор, вроде теперь должно быть норм

2022-08-13 04:25 UTC, kuzen0211 approved these changes

2022-08-13 04:26 UTC, merged